# Generated by Django 5.2.6 on 2025-09-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20, unique=True, verbose_name='Período')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('variacion_mensual', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Variación Mensual (%)')),
                ('variacion_anual', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Variación Anual (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dato IPC',
                'verbose_name_plural': 'Datos IPC',
                'ordering': ['-fecha'],
            },
        ),
    ]
